package com.android.awells.coursetrackerroom.data;

/**
 * Created by Owner on 1/11/2018.
 */

import android.arch.persistence.room.Database;
import android.arch.persistence.room.Room;
import android.arch.persistence.room.RoomDatabase;
import android.content.Context;
import android.support.annotation.VisibleForTesting;
/**
 * The Room database.
 */
@Database(entities = {Term.class, Course.class}, version = 1)
public abstract class CourseTrackerDatabase extends RoomDatabase{

    /**
     * @return The DAO for the Term table.
     */
    public abstract TermDao term();

    /**
     * @return The DAO for the Course table.
     */
    public abstract CourseDao course();

    /** The only instance */
    private static CourseTrackerDatabase sInstance;

    /**
     * Gets the singleton instance of SampleDatabase.
     *
     * @param context The context.
     * @return The singleton instance of SampleDatabase.
     */
    public static synchronized CourseTrackerDatabase getInstance(Context context) {
        if (sInstance == null) {
            sInstance = Room
                    .databaseBuilder(context.getApplicationContext(), CourseTrackerDatabase.class, "TrackerDB")
                    .allowMainThreadQueries() //todo SHORT TERM SOLUTION JUST FOR THIS SCHOOL PROJECT
                    .build();
            sInstance.populateInitialData();
        }
        return sInstance;
    }

    /**
     * Switches the internal implementation with an empty in-memory database.
     *
     * @param context The context.
     */
    @VisibleForTesting
    public static void switchToInMemory(Context context) {
        sInstance = Room.inMemoryDatabaseBuilder(context.getApplicationContext(),
                CourseTrackerDatabase.class).build();
    }

    /**
     * Inserts the dummy data into the database if it is currently empty.
     */
    private void populateInitialData() {
        if (term().count() == 0) {
            beginTransaction();
            try {
                //Add 5 terms
                for (int i = 0; i < Term.TERMS.length; i++) {
                    Term term = new Term();
                    term.setTitle(Term.TERMS[i]);
                    term().insert(term);
                }

                //Add 10 courses that reference previously added terms
                for (int i = 0; i < Term.TERMS.length; i++) {
                    Course course1 = new Course();
                    course1.setTitle(Course.COURSES[i]);
                    course1.setTermId(i + 1); //+1 because autogenerated IDs start at 1
                    course().insert(course1);

                    Course course2 = new Course();
                    course2.setTitle(Course.COURSES[i + 1]);
                    course2.setTermId(i + 1);//+1 because autogenerated IDs start at 1
                    course().insert(course2);
                }

                setTransactionSuccessful();
            } finally {
                endTransaction();
            }
        }
    }
}
